import ZustandProvider from '@/components/zustandProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Beer Recipes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='header text-center text-3xl text-fuchsia-400 p-3'>Beer Recipes</header>
        <ZustandProvider>{children}</ZustandProvider></body>
    </html>
  )
}
